# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48fc7cbd0c8d332664b02fea156cea3f56d076e9f80db53d389813d50ed349ac3e2068eb8019b31516f328f77bb7760bfb5f6c7aa70b6219a83de58e4578aa62

test:
  secret_key_base: ec4df39ddc16d00ae7488122fa1b884d30420191cc9a2040c9c8a8b53e9c596e09e31a7741e73adb911f4debc7427693e63a9e1997527b0477be87044500887b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
